# Generated by Django 4.2.17 on 2026-06-29 19:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Tên công ty')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('business_license', models.CharField(max_length=50, verbose_name='Mã giấy phép kinh doanh')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin kiểm duyệt doanh nghiệp', verbose_name='Đã xác minh')),
                ('trust_score', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Điểm uy tín')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ Doanh nghiệp',
                'verbose_name_plural': 'Hồ sơ Doanh nghiệp',
                'db_table': 'employer_profile',
            },
        ),
        migrations.CreateModel(
            name='JobShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề ca làm')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả công việc')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('wage_per_hour', models.DecimalField(decimal_places=0, help_text='Đơn vị: VNĐ', max_digits=10, verbose_name='Lương/giờ (VNĐ)')),
                ('required_students', models.PositiveIntegerField(default=1, verbose_name='Số sinh viên cần')),
                ('status', models.CharField(choices=[('Open', 'Đang mở'), ('Filled', 'Đã đủ người'), ('Closed', 'Đã đóng')], default='Open', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_shifts', to='core.employerprofile', verbose_name='Doanh nghiệp')),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
                'db_table': 'job_shift',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(help_text='Tự động trích xuất từ email', max_length=20, unique=True, verbose_name='Mã sinh viên')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('class_name', models.CharField(max_length=50, verbose_name='Lớp sinh hoạt')),
                ('major', models.CharField(max_length=100, verbose_name='Ngành học')),
                ('trust_score', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Điểm uy tín')),
                ('is_profile_complete', models.BooleanField(default=False, verbose_name='Đã hoàn thiện hồ sơ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ Sinh viên',
                'verbose_name_plural': 'Hồ sơ Sinh viên',
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')], verbose_name='Ngày trong tuần')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu rảnh')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc rảnh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='core.studentprofile', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Khung giờ rảnh',
                'verbose_name_plural': 'Khung giờ rảnh',
                'db_table': 'time_block',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Chờ duyệt'), ('CheckIn', 'Đã check-in'), ('CheckOut', 'Đã check-out'), ('Completed', 'Hoàn thành')], default='Pending', max_length=10, verbose_name='Trạng thái')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian check-in')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian check-out')),
                ('rating_from_employer', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá từ doanh nghiệp')),
                ('rating_from_student', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá từ sinh viên')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày ứng tuyển')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.jobshift', verbose_name='Ca làm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.studentprofile', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Đơn ứng tuyển',
                'verbose_name_plural': 'Đơn ứng tuyển',
                'db_table': 'shift_application',
                'unique_together': {('shift', 'student')},
            },
        ),
    ]
