# Generated by Django 4.2.17 on 2026-07-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='portal_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Mật khẩu portal'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portal_school',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Trường portal'),
        ),
        migrations.CreateModel(
            name='StudySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Mã học phần')),
                ('course_name', models.CharField(max_length=200, verbose_name='Tên học phần')),
                ('credits', models.CharField(blank=True, default='', max_length=10, verbose_name='Số tín chỉ')),
                ('lop', models.CharField(blank=True, default='', max_length=100, verbose_name='Lớp học phần')),
                ('weekday', models.IntegerField(choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')], verbose_name='Ngày trong tuần')),
                ('tiet', models.CharField(max_length=50, verbose_name='Tiết học')),
                ('phong', models.CharField(blank=True, default='', max_length=50, verbose_name='Phòng học')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_schedules', to='core.studentprofile', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Lịch học sinh viên',
                'verbose_name_plural': 'Lịch học sinh viên',
                'db_table': 'study_schedule',
            },
        ),
    ]
