# Generated by Django 4.2.17 on 2026-07-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentprofile_portal_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyschedule',
            name='giang_vien',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Giảng viên'),
        ),
        migrations.AddField(
            model_name='studyschedule',
            name='link_meet',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Link Google Meet'),
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Mã học phần')),
                ('course_name', models.CharField(max_length=200, verbose_name='Tên học phần')),
                ('exam_date', models.DateField(verbose_name='Ngày thi')),
                ('exam_time', models.TimeField(verbose_name='Giờ thi')),
                ('room', models.CharField(blank=True, default='', max_length=50, verbose_name='Phòng thi')),
                ('exam_format', models.CharField(blank=True, default='Trắc nghiệm', max_length=100, verbose_name='Hình thức thi')),
                ('sbd', models.CharField(blank=True, default='', max_length=20, verbose_name='Số báo danh')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='core.studentprofile', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Lịch thi sinh viên',
                'verbose_name_plural': 'Lịch thi sinh viên',
                'db_table': 'exam_schedule',
                'ordering': ['exam_date', 'exam_time'],
            },
        ),
    ]
