# Generated by Django 4.2.17 on 2026-07-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studyschedule_giang_vien_studyschedule_link_meet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='student_avatars/', verbose_name='Ảnh đại diện'),
        ),
    ]
