# Generated by Django 4.2.17 on 2026-07-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobshift',
            name='target_major',
            field=models.CharField(choices=[('Tất cả', 'Tất cả các ngành'), ('Công nghệ thông tin', 'Công nghệ thông tin'), ('Kỹ thuật phần mềm', 'Kỹ thuật phần mềm'), ('Khoa học máy tính', 'Khoa học máy tính'), ('Hệ thống thông tin quản lý', 'Hệ thống thông tin quản lý'), ('Quản trị kinh doanh', 'Quản trị kinh doanh'), ('Kế toán', 'Kế toán'), ('Tài chính ngân hàng', 'Tài chính ngân hàng'), ('Kỹ thuật cơ khí', 'Kỹ thuật cơ khí'), ('Kỹ thuật điện', 'Kỹ thuật điện'), ('Tự động hóa', 'Tự động hóa'), ('Y đa khoa', 'Y đa khoa'), ('Dược học', 'Dược học'), ('Ngôn ngữ Anh', 'Ngôn ngữ Anh'), ('Ngôn ngữ Trung Quốc', 'Ngôn ngữ Trung Quốc'), ('Sư phạm toán', 'Sư phạm toán'), ('Sư phạm văn', 'Sư phạm văn'), ('Khác', 'Khác')], default='Tất cả', max_length=100, verbose_name='Ngành yêu cầu'),
        ),
        migrations.AddField(
            model_name='jobshift',
            name='target_school',
            field=models.CharField(choices=[('Tất cả', 'Tất cả các trường'), ('ictu', 'ĐH CNTT & Truyền thông (ICTU)'), ('tueba', 'ĐH Kinh tế & QTKD (TUEBA)'), ('tnut', 'ĐH Kỹ thuật Công nghiệp (TNUT)'), ('tnus', 'ĐH Khoa học (TNUS)'), ('tump', 'ĐH Y Dược (TUMP)'), ('tnue', 'ĐH Sư phạm (TNUE)'), ('sfl', 'Trường Ngoại ngữ (SFL)')], default='Tất cả', max_length=50, verbose_name='Trường yêu cầu'),
        ),
    ]
