# Generated by Django 4.2.17 on 2026-07-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobshift_target_major_jobshift_target_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobshift',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hạn đăng ký ca làm'),
        ),
        migrations.AlterField(
            model_name='shiftapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ duyệt'), ('CheckIn', 'Đã check-in'), ('CheckOut', 'Đã check-out'), ('Completed', 'Hoàn thành'), ('Failed', 'Không hoàn thành')], default='Pending', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
